// GENERATED by flutter_l10n_ast – do not edit manually.
// Re-run the tool after adding new strings.

import 'package:flutter/widgets.dart';
import 'package:blood_bridge/l10n/app_localizations.dart';

/// Quick accessor:  context.l10n.someKey
extension BuildContextL10n on BuildContext {
  AppLocalizations get l10n => AppLocalizations.of(this)!;
}
